linters:
  enable:
    - cyclop
    - funlen
    - gocognit
    - nestif

linters-settings:
  cyclop:
    max-complexity: 15
  funlen:
    lines: 80
    statements: 50
  gocognit:
    min-complexity: 20
  nestif:
    min-complexity: 5

issues:
  exclude-rules:
    - path: _test\.go
      linters: [funlen, gocognit, cyclop, errcheck]
