linters:
  enable:
    - cyclop
    - funlen
    - gocognit
    - nestif
    - revive

linters-settings:
  cyclop:
    max-complexity: 15
  funlen:
    lines: 80
    statements: 50
  gocognit:
    min-complexity: 20
  nestif:
    min-complexity: 5
  revive:
    rules:
      - name: file-length-limit
        arguments: [{max: 500}]

issues:
  exclude-rules:
    - path: _test\.go
      linters: [funlen, gocognit, cyclop, errcheck, revive]
