version: 2

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: codepush
    binary: codepush
    main: ./cmd/codepush
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
    ignore:
      - goos: linux
        goarch: arm64

archives:
  - id: codepush
    format: binary
    name_template: >-
      codepush-
      {{- if eq .Os "darwin" }}Darwin
      {{- else if eq .Os "linux" }}Linux
      {{- end }}-
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "arm64" }}arm64
      {{- end }}

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^ci:'

release:
  github:
    owner: bitrise-io
    name: bitrise-plugins-codepush-cli
  draft: false
  prerelease: auto
  name_template: "{{.Version}}"
