---
format_version: '15'
default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git
project_type: other
trigger_map:
- push_branch: main
  pipeline: pipeline_ci
- pull_request_target_branch: main
  pipeline: pipeline_ci
- tag: "*.*.*"
  pipeline: pipeline_release
pipelines:
  pipeline_ci:
    workflows:
      ci: {}
  pipeline_release:
    workflows:
      release: {}
workflows:
  ci:
    steps:
    - git-clone@8: {}
    - go-list@1: {}
    - script@1:
        title: Build
        inputs:
        - content: go build ./cmd/codepush
    - script@1:
        title: Test
        inputs:
        - content: go test -coverprofile="$BITRISE_DEPLOY_DIR/coverage.out" ./...
    - script@1:
        title: Check test coverage
        inputs:
        - content: |
            #!/bin/bash
            set -euo pipefail

            THRESHOLD=75
            COVERPROFILE="$BITRISE_DEPLOY_DIR/coverage.out"

            if [ ! -f "$COVERPROFILE" ]; then
                echo "FAIL: coverage profile not found at $COVERPROFILE"
                exit 1
            fi

            COVERAGE=$(go tool cover -func="$COVERPROFILE" | grep ^total: | awk '{print $3}' | tr -d '%')

            if [ -z "$COVERAGE" ]; then
                echo "FAIL: could not determine coverage"
                exit 1
            fi

            PASS=$(awk "BEGIN {print ($COVERAGE >= $THRESHOLD) ? 1 : 0}")

            if [ "$PASS" -eq 1 ]; then
                echo "PASS: coverage ${COVERAGE}% >= ${THRESHOLD}% threshold"
            else
                echo "FAIL: coverage ${COVERAGE}% < ${THRESHOLD}% threshold"
                exit 1
            fi
    - script@1:
        title: Check version sync
        inputs:
        - content: |
            #!/bin/bash
            set -euo pipefail

            CODE_VERSION=$(grep 'version = ' cmd/codepush/main.go | head -1 | sed 's/.*"\(.*\)".*/\1/')
            PLUGIN_VERSION=$(grep -oP 'download/\K[^/]+' bitrise-plugin.yml | head -1)

            if [ -z "$CODE_VERSION" ]; then
                echo "FAIL: could not parse version from cmd/codepush/main.go"
                exit 1
            fi

            if [ -z "$PLUGIN_VERSION" ]; then
                echo "FAIL: could not parse version from bitrise-plugin.yml"
                exit 1
            fi

            if [ "$CODE_VERSION" != "$PLUGIN_VERSION" ]; then
                echo "FAIL: version mismatch"
                echo "  cmd/codepush/main.go: $CODE_VERSION"
                echo "  bitrise-plugin.yml:   $PLUGIN_VERSION"
                exit 1
            fi

            echo "PASS: version $CODE_VERSION is consistent"
    - script@1:
        title: go vet
        inputs:
        - content: go vet ./...
    - script@1:
        title: golangci-lint
        inputs:
        - content: |
            #!/bin/bash
            set -euo pipefail
            curl -sSfL https://golangci-lint.run/install.sh | sh -s -- -b "$(go env GOPATH)/bin" v1.64.8
            "$(go env GOPATH)/bin/golangci-lint" run
  release:
    steps:
    - git-clone@8:
        inputs:
        - clone_depth: "0"
    - go-list@1: {}
    - script@1:
        title: Validate tag matches code version
        inputs:
        - content: |
            #!/bin/bash
            set -euo pipefail

            TAG_VERSION="$BITRISE_GIT_TAG"
            CODE_VERSION=$(grep 'version = ' cmd/codepush/main.go | head -1 | sed 's/.*"\(.*\)".*/\1/')
            PLUGIN_VERSION=$(grep -oP 'download/\K[^/]+' bitrise-plugin.yml | head -1)

            echo "Tag version:    $TAG_VERSION"
            echo "Code version:   $CODE_VERSION"
            echo "Plugin version: $PLUGIN_VERSION"

            if [ "$TAG_VERSION" != "$CODE_VERSION" ]; then
                echo "FAIL: tag $TAG_VERSION does not match main.go version $CODE_VERSION"
                exit 1
            fi
            if [ "$TAG_VERSION" != "$PLUGIN_VERSION" ]; then
                echo "FAIL: tag $TAG_VERSION does not match bitrise-plugin.yml version $PLUGIN_VERSION"
                exit 1
            fi
            echo "PASS: all versions are $TAG_VERSION"
    - script@1:
        title: Install GoReleaser
        inputs:
        - content: |
            #!/bin/bash
            set -euo pipefail
            curl -sSfL https://github.com/goreleaser/goreleaser/releases/latest/download/goreleaser_Linux_x86_64.tar.gz \
              | tar -xz -C /usr/local/bin goreleaser
            goreleaser --version
    - script@1:
        title: Run GoReleaser
        inputs:
        - content: |
            #!/bin/bash
            set -euo pipefail
            goreleaser release --clean
